### ISSUE TITLE
gulp generate --watch produces error; can't figure out watch functionality

### ISSUE THREAD

**Issue by joshualinog** [VARIANTE/generator-vars-jekyll#1]
@andrewscwei 
![image](https://cloud.githubusercontent.com/assets/1839603/10980069/10004990-83ce-11e5-98a6-d1e893bf0199.png)

**Comment by joshualinog** [comment]
love the idea so far; want to make this work; so far using the --watch task on serve, build, and generate tasks do not seem to actually facilitate watching. i.e. when I run gulp build --watch, and then change the index.html file in "app/" nothing happens.

**Comment by andrewscwei** [comment]
Hello @jajourda, thanks for reporting the issue. I just had a chance to take a deeper look, are you by chance running `--watch` without `--debug`? Watching is only meant to work in `--debug` to avoid the overhead of post-processing assets, hence speeding up development iteration. I actually put in a warning message in other Gulp tasks that support watch to notify `--debug` only, except for the `generate` task. That was my bad and I will add that in the next commit.

In the meantime, please see if tagging `--debug` along with `--watch` works for you. Feel free to let me know if there are still issues. As a side note, you can do `--d` and `--w` instead for less typing (there are short notations for every flag, see `.taskconfig` for more).

**Comment by joshualinog** [comment]
thanks bro; big help yeah, i was running gulp generate --watch; after running gulp generate --watch --debug it worked... also i was confused because i confused myself :) initially i was trying to run gulp serve --debug --watch AND THEN just change index.html to test for changes... no changes detected.... now I see I need to run gulp serve --debug --watch AND THEN in another terminal tab/instance run gulp generate --watch --debug. just curious what caused you to split up your gulp tasks this way?

**Comment by andrewscwei** [comment]
The tasks were divided up so they can be run individually if needed. Normally during development, I would strongly recommend just do `gulp --d --w --s`. This would generate your Jekyll project, compile all assets, serve your project when done and watch for file changes as well (and of course live reloading the browser when changes come in).

**Comment by joshualinog** [comment]
@andrewscwei  i'm new to contributing to github, so be patient :)  what about an explicit example being provided like this pull request I just made: https://github.com/VARIANTE/generator-vars-jekyll/pull/2

**Comment by andrewscwei** [comment]
I am ACTUALLY right in the middle of editing the README for clearer documentation as we speak and was just about to push it to head :) I am sorry but I will have to kindly decline your PR!

**Comment by andrewscwei** [comment]
All should be well in 05e6705.
