### ISSUE TITLE
rev task regex bug

### ISSUE THREAD

**Issue by k-funk** [VARIANTE/generator-vars-jekyll#12]
**To reproduce:**
1. `git clone git@github.com:k-funk/generator-vars-jekyll-rev-bug.git && cd generator-vars-jekyll-rev-bug`
2. `npm install && bundle install --path vendor/bundle`
3. `npm run prod`
4. `cat public/assets/stylesheets/main-1e43194ffd.css` (filename/hash might not be exactly the same)
5. Check out the filenames for the `woff`/`woff2` fonts. Observe that they have the same hash (`fa2772327f`), but have different file extensions
6. `ls public/assets/fonts/`. See that the files have different hashes:
   - `...-448c34a56d.woff2`
   - `...-fa2772327f.woff`

I think that the regex matching in rev is matching `woff` before it gets a chance to match `woff2`.

**Comment by andrewscwei** [comment]
Thanks for the providing the example. This should now be fixed in 4d46b88515e9d014b78ab8eb3a8487a985754d7b.

**Comment by k-funk** [comment]
Thanks!
