### ISSUE TITLE
generate task and front matter

### ISSUE THREAD

**Issue by joshualinog** [VARIANTE/generator-vars-jekyll#3]
@andrewscwei Is there any way to put a environment flag on the generate/build task that still minifies, BUT keeps the front matter intact on the .html/.md files? cloudcannon is a cms solution that uses front matter in its client editing solution.

**Comment by andrewscwei** [comment]
Short answer: no.

Front matters are parsed by the Jekyll generator, so obviously they won't be present in generated files. If you are using CloudCannon then you shouldn't need the Gulp pipeline provided by this generator. I believe CloudCannon handles all asset compression (minifying JS/CSS) for you when it deploys your site.
